services:
  llama_cpp_embedding_server:
    image: ghcr.io/ggml-org/llama.cpp:server-b6402
    platform: linux/amd64
    restart: unless-stopped
    networks:
      - web
    volumes:
      - ./models:/models:ro
    command: ["--model", "/models/embeddinggemma-300M-BF16.gguf", "--port", "8000", "--host", "0.0.0.0", "--embedding"]
    ports:
      - "8001:8000"

  llama_cpp_llm_server:
    image: ghcr.io/ggml-org/llama.cpp:server-b6402
    platform: linux/amd64
    restart: unless-stopped
    networks:
      - web
    volumes:
      - ./models:/models:ro
    command: ["--model", "/models/Llama-3.2-1B-Instruct-Q4_K_S.gguf", "--port", "8000", "--host", "0.0.0.0", "-n", "512"]
    ports:
      - "8002:8000"

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: chatdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db
    ports:
      - "5432:5432"

  api:
    build: ./backend
    restart: unless-stopped
    networks: 
      - web
      - db
    security_opt: [ "no-new-privileges:true" ]
    cap_drop: [ "ALL" ]
    volumes:
      - ./backend/logs:/app/logs:rw
      - vector_store:/app/stores
    environment:
      - DEBUG=true
      - ALLOWED_ORIGINS=["*"]
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/chatdb
      - LLAMA_CPP_EMBEDDING_SERVER_URL=http://llama_cpp_embedding_server:8000
      - LLAMA_CPP_LLM_SERVER_URL=http://llama_cpp_llm_server:8000
    depends_on:
      - postgres
    env_file:
      - path: ./.env
        required: false
    develop:
      watch:
        - action: sync
          path: ./backend/src
          target: /app/src
    ports:
      - "8000:8000"
    command: ["uv", "run", "uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

networks:
  web:
    driver: bridge
  db:
    driver: bridge

volumes:
  postgres_data:
  vector_store:
