services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: chatdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks: 
      - db
    security_opt: [ "no-new-privileges:true" ]

  api:
    build: ./backend
    restart: unless-stopped
    networks: 
      - web
      - db
    security_opt: [ "no-new-privileges:true" ]
    cap_drop: [ "ALL" ]
    volumes:
      - ./backend/logs:/app/logs:rw
    environment:
      - DEBUG=false
      - ALLOWED_ORIGINS=["chat.andrewchu.ca"]
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/chatdb
    depends_on:
      - postgres
    env_file:
      - path: ./.env
        required: false

  nginx:
    image: nginx:1.29.0
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certs:/etc/letsencrypt:ro
      - /srv/nginx-logs:/var/log/nginx
      - nginx-cache:/var/cache/nginx
      - ./webroot:/var/www/certbot:ro
    depends_on: [api]
    networks: 
      - web
    security_opt: [ "no-new-privileges:true" ]
    cap_drop: [ "ALL" ]
    cap_add:
      - CHOWN             # allow entrypoint to chown cache dir
      - NET_BIND_SERVICE  # allow binding to 80/443
      - SETUID            # master -> worker user drop
      - SETGID            # master -> worker group drop

  certbot:
    image: certbot/certbot:arm64v8-latest
    restart: unless-stopped
    volumes:
      - ./certs:/etc/letsencrypt
      - ./webroot:/var/www/certbot
    entrypoint: /bin/sh
      # keep the container idle until you run commands
    command: -c "sleep infinity"

networks:
  web:
    driver: bridge
  db:
    driver: bridge

volumes:
  nginx-cache:
  postgres_data:

